#!/usr/bin/env python3
"""
Location mapping for L4D2 Archipelago integration
Maps game events to Archipelago location IDs
"""

# Base ID from Locations.py
BASE_ID = 69420000

# Map campaign + chapter + character to location ID
LOCATION_MAP = {
    # Dead Center
    ("c1m1_hotel", "ellis"): BASE_ID + 0,
    ("c1m1_hotel", "rochelle"): BASE_ID + 1,
    ("c1m1_hotel", "coach"): BASE_ID + 2,
    ("c1m1_hotel", "nick"): BASE_ID + 3,
    ("c1m2_streets", "ellis"): BASE_ID + 4,
    ("c1m2_streets", "rochelle"): BASE_ID + 5,
    ("c1m2_streets", "coach"): BASE_ID + 6,
    ("c1m2_streets", "nick"): BASE_ID + 7,
    ("c1m3_mall", "ellis"): BASE_ID + 8,
    ("c1m3_mall", "rochelle"): BASE_ID + 9,
    ("c1m3_mall", "coach"): BASE_ID + 10,
    ("c1m3_mall", "nick"): BASE_ID + 11,
    ("c1m4_atrium", "ellis"): BASE_ID + 12,
    ("c1m4_atrium", "rochelle"): BASE_ID + 13,
    ("c1m4_atrium", "coach"): BASE_ID + 14,
    ("c1m4_atrium", "nick"): BASE_ID + 15,
    ("c1m2_streets", "cola_bottles"): BASE_ID + 16,
    
    # The Passing
    ("c6m1_riverbank", "ellis"): BASE_ID + 17,
    ("c6m1_riverbank", "rochelle"): BASE_ID + 18,
    ("c6m1_riverbank", "coach"): BASE_ID + 19,
    ("c6m1_riverbank", "nick"): BASE_ID + 20,
    ("c6m2_bedlam", "ellis"): BASE_ID + 21,
    ("c6m2_bedlam", "rochelle"): BASE_ID + 22,
    ("c6m2_bedlam", "coach"): BASE_ID + 23,
    ("c6m2_bedlam", "nick"): BASE_ID + 24,
    ("c6m3_port", "ellis"): BASE_ID + 25,
    ("c6m3_port", "rochelle"): BASE_ID + 26,
    ("c6m3_port", "coach"): BASE_ID + 27,
    ("c6m3_port", "nick"): BASE_ID + 28,
    
    # Dark Carnival
    ("c2m1_highway", "ellis"): BASE_ID + 29,
    ("c2m1_highway", "rochelle"): BASE_ID + 30,
    ("c2m1_highway", "coach"): BASE_ID + 31,
    ("c2m1_highway", "nick"): BASE_ID + 32,
    ("c2m2_fairgrounds", "ellis"): BASE_ID + 33,
    ("c2m2_fairgrounds", "rochelle"): BASE_ID + 34,
    ("c2m2_fairgrounds", "coach"): BASE_ID + 35,
    ("c2m2_fairgrounds", "nick"): BASE_ID + 36,
    ("c2m3_coaster", "ellis"): BASE_ID + 37,
    ("c2m3_coaster", "rochelle"): BASE_ID + 38,
    ("c2m3_coaster", "coach"): BASE_ID + 39,
    ("c2m3_coaster", "nick"): BASE_ID + 40,
    ("c2m4_barns", "ellis"): BASE_ID + 41,
    ("c2m4_barns", "rochelle"): BASE_ID + 42,
    ("c2m4_barns", "coach"): BASE_ID + 43,
    ("c2m4_barns", "nick"): BASE_ID + 44,
    ("c2m5_concert", "ellis"): BASE_ID + 45,
    ("c2m5_concert", "rochelle"): BASE_ID + 46,
    ("c2m5_concert", "coach"): BASE_ID + 47,
    ("c2m5_concert", "nick"): BASE_ID + 48,
    
    # Swamp Fever
    ("c3m1_plankcountry", "ellis"): BASE_ID + 49,
    ("c3m1_plankcountry", "rochelle"): BASE_ID + 50,
    ("c3m1_plankcountry", "coach"): BASE_ID + 51,
    ("c3m1_plankcountry", "nick"): BASE_ID + 52,
    ("c3m2_swamp", "ellis"): BASE_ID + 53,
    ("c3m2_swamp", "rochelle"): BASE_ID + 54,
    ("c3m2_swamp", "coach"): BASE_ID + 55,
    ("c3m2_swamp", "nick"): BASE_ID + 56,
    ("c3m3_shantytown", "ellis"): BASE_ID + 57,
    ("c3m3_shantytown", "rochelle"): BASE_ID + 58,
    ("c3m3_shantytown", "coach"): BASE_ID + 59,
    ("c3m3_shantytown", "nick"): BASE_ID + 60,
    ("c3m4_plantation", "ellis"): BASE_ID + 61,
    ("c3m4_plantation", "rochelle"): BASE_ID + 62,
    ("c3m4_plantation", "coach"): BASE_ID + 63,
    ("c3m4_plantation", "nick"): BASE_ID + 64,
    
    # Hard Rain
    ("c4m1_milltown_a", "ellis"): BASE_ID + 65,
    ("c4m1_milltown_a", "rochelle"): BASE_ID + 66,
    ("c4m1_milltown_a", "coach"): BASE_ID + 67,
    ("c4m1_milltown_a", "nick"): BASE_ID + 68,
    ("c4m2_sugarmill_a", "ellis"): BASE_ID + 69,
    ("c4m2_sugarmill_a", "rochelle"): BASE_ID + 70,
    ("c4m2_sugarmill_a", "coach"): BASE_ID + 71,
    ("c4m2_sugarmill_a", "nick"): BASE_ID + 72,
    ("c4m3_sugarmill_b", "ellis"): BASE_ID + 73,
    ("c4m3_sugarmill_b", "rochelle"): BASE_ID + 74,
    ("c4m3_sugarmill_b", "coach"): BASE_ID + 75,
    ("c4m3_sugarmill_b", "nick"): BASE_ID + 76,
    ("c4m4_milltown_b", "ellis"): BASE_ID + 77,
    ("c4m4_milltown_b", "rochelle"): BASE_ID + 78,
    ("c4m4_milltown_b", "coach"): BASE_ID + 79,
    ("c4m4_milltown_b", "nick"): BASE_ID + 80,
    ("c4m5_milltown_escape", "ellis"): BASE_ID + 81,
    ("c4m5_milltown_escape", "rochelle"): BASE_ID + 82,
    ("c4m5_milltown_escape", "coach"): BASE_ID + 83,
    ("c4m5_milltown_escape", "nick"): BASE_ID + 84,
    
    # The Parish
    ("c5m1_waterfront", "ellis"): BASE_ID + 85,
    ("c5m1_waterfront", "rochelle"): BASE_ID + 86,
    ("c5m1_waterfront", "coach"): BASE_ID + 87,
    ("c5m1_waterfront", "nick"): BASE_ID + 88,
    ("c5m2_park", "ellis"): BASE_ID + 89,
    ("c5m2_park", "rochelle"): BASE_ID + 90,
    ("c5m2_park", "coach"): BASE_ID + 91,
    ("c5m2_park", "nick"): BASE_ID + 92,
    ("c5m3_cemetery", "ellis"): BASE_ID + 93,
    ("c5m3_cemetery", "rochelle"): BASE_ID + 94,
    ("c5m3_cemetery", "coach"): BASE_ID + 95,
    ("c5m3_cemetery", "nick"): BASE_ID + 96,
    ("c5m4_quarter", "ellis"): BASE_ID + 97,
    ("c5m4_quarter", "rochelle"): BASE_ID + 98,
    ("c5m4_quarter", "coach"): BASE_ID + 99,
    ("c5m4_quarter", "nick"): BASE_ID + 100,
    ("c5m5_bridge", "ellis"): BASE_ID + 101,
    ("c5m5_bridge", "rochelle"): BASE_ID + 102,
    ("c5m5_bridge", "coach"): BASE_ID + 103,
    ("c5m5_bridge", "nick"): BASE_ID + 104,
    
    # The Sacrifice
    ("c7m1_docks", "francis"): BASE_ID + 105,
    ("c7m1_docks", "bill"): BASE_ID + 106,
    ("c7m1_docks", "zoey"): BASE_ID + 107,
    ("c7m1_docks", "louis"): BASE_ID + 108,
    ("c7m2_barge", "francis"): BASE_ID + 109,
    ("c7m2_barge", "bill"): BASE_ID + 110,
    ("c7m2_barge", "zoey"): BASE_ID + 111,
    ("c7m2_barge", "louis"): BASE_ID + 112,
    ("c7m3_port", "francis"): BASE_ID + 113,
    ("c7m3_port", "bill"): BASE_ID + 114,
    ("c7m3_port", "zoey"): BASE_ID + 115,
    ("c7m3_port", "louis"): BASE_ID + 116,
    
    # No Mercy
    ("c8m1_apartment", "francis"): BASE_ID + 117,
    ("c8m1_apartment", "bill"): BASE_ID + 118,
    ("c8m1_apartment", "zoey"): BASE_ID + 119,
    ("c8m1_apartment", "louis"): BASE_ID + 120,
    ("c8m2_subway", "francis"): BASE_ID + 121,
    ("c8m2_subway", "bill"): BASE_ID + 122,
    ("c8m2_subway", "zoey"): BASE_ID + 123,
    ("c8m2_subway", "louis"): BASE_ID + 124,
    ("c8m3_sewers", "francis"): BASE_ID + 125,
    ("c8m3_sewers", "bill"): BASE_ID + 126,
    ("c8m3_sewers", "zoey"): BASE_ID + 127,
    ("c8m3_sewers", "louis"): BASE_ID + 128,
    ("c8m4_interior", "francis"): BASE_ID + 129,
    ("c8m4_interior", "bill"): BASE_ID + 130,
    ("c8m4_interior", "zoey"): BASE_ID + 131,
    ("c8m4_interior", "louis"): BASE_ID + 132,
    ("c8m5_rooftop", "francis"): BASE_ID + 133,
    ("c8m5_rooftop", "bill"): BASE_ID + 134,
    ("c8m5_rooftop", "zoey"): BASE_ID + 135,
    ("c8m5_rooftop", "louis"): BASE_ID + 136,
    
    # Crash Course
    ("c9m1_alleys", "francis"): BASE_ID + 137,
    ("c9m1_alleys", "bill"): BASE_ID + 138,
    ("c9m1_alleys", "zoey"): BASE_ID + 139,
    ("c9m1_alleys", "louis"): BASE_ID + 140,
    ("c9m2_lots", "francis"): BASE_ID + 141,
    ("c9m2_lots", "bill"): BASE_ID + 142,
    ("c9m2_lots", "zoey"): BASE_ID + 143,
    ("c9m2_lots", "louis"): BASE_ID + 144,
    
    # Death Toll
    ("c10m1_caves", "francis"): BASE_ID + 145,
    ("c10m1_caves", "bill"): BASE_ID + 146,
    ("c10m1_caves", "zoey"): BASE_ID + 147,
    ("c10m1_caves", "louis"): BASE_ID + 148,
    ("c10m2_drainage", "francis"): BASE_ID + 149,
    ("c10m2_drainage", "bill"): BASE_ID + 150,
    ("c10m2_drainage", "zoey"): BASE_ID + 151,
    ("c10m2_drainage", "louis"): BASE_ID + 152,
    ("c10m3_ranchhouse", "francis"): BASE_ID + 153,
    ("c10m3_ranchhouse", "bill"): BASE_ID + 154,
    ("c10m3_ranchhouse", "zoey"): BASE_ID + 155,
    ("c10m3_ranchhouse", "louis"): BASE_ID + 156,
    ("c10m4_mainstreet", "francis"): BASE_ID + 157,
    ("c10m4_mainstreet", "bill"): BASE_ID + 158,
    ("c10m4_mainstreet", "zoey"): BASE_ID + 159,
    ("c10m4_mainstreet", "louis"): BASE_ID + 160,
    ("c10m5_houseboat", "francis"): BASE_ID + 161,
    ("c10m5_houseboat", "bill"): BASE_ID + 162,
    ("c10m5_houseboat", "zoey"): BASE_ID + 163,
    ("c10m5_houseboat", "louis"): BASE_ID + 164,
    
    # Dead Air
    ("c11m1_greenhouse", "francis"): BASE_ID + 165,
    ("c11m1_greenhouse", "bill"): BASE_ID + 166,
    ("c11m1_greenhouse", "zoey"): BASE_ID + 167,
    ("c11m1_greenhouse", "louis"): BASE_ID + 168,
    ("c11m2_offices", "francis"): BASE_ID + 169,
    ("c11m2_offices", "bill"): BASE_ID + 170,
    ("c11m2_offices", "zoey"): BASE_ID + 171,
    ("c11m2_offices", "louis"): BASE_ID + 172,
    ("c11m3_garage", "francis"): BASE_ID + 173,
    ("c11m3_garage", "bill"): BASE_ID + 174,
    ("c11m3_garage", "zoey"): BASE_ID + 175,
    ("c11m3_garage", "louis"): BASE_ID + 176,
    ("c11m4_terminal", "francis"): BASE_ID + 177,
    ("c11m4_terminal", "bill"): BASE_ID + 178,
    ("c11m4_terminal", "zoey"): BASE_ID + 179,
    ("c11m4_terminal", "louis"): BASE_ID + 180,
    ("c11m5_runway", "francis"): BASE_ID + 181,
    ("c11m5_runway", "bill"): BASE_ID + 182,
    ("c11m5_runway", "zoey"): BASE_ID + 183,
    ("c11m5_runway", "louis"): BASE_ID + 184,
    
    # Blood Harvest
    ("c12m1_hilltop", "francis"): BASE_ID + 185,
    ("c12m1_hilltop", "bill"): BASE_ID + 186,
    ("c12m1_hilltop", "zoey"): BASE_ID + 187,
    ("c12m1_hilltop", "louis"): BASE_ID + 188,
    ("c12m2_traintunnel", "francis"): BASE_ID + 189,
    ("c12m2_traintunnel", "bill"): BASE_ID + 190,
    ("c12m2_traintunnel", "zoey"): BASE_ID + 191,
    ("c12m2_traintunnel", "louis"): BASE_ID + 192,
    ("c12m3_bridge", "francis"): BASE_ID + 193,
    ("c12m3_bridge", "bill"): BASE_ID + 194,
    ("c12m3_bridge", "zoey"): BASE_ID + 195,
    ("c12m3_bridge", "louis"): BASE_ID + 196,
    ("c12m4_barn", "francis"): BASE_ID + 197,
    ("c12m4_barn", "bill"): BASE_ID + 198,
    ("c12m4_barn", "zoey"): BASE_ID + 199,
    ("c12m4_barn", "louis"): BASE_ID + 200,
    ("c12m5_cornfield", "francis"): BASE_ID + 201,
    ("c12m5_cornfield", "bill"): BASE_ID + 202,
    ("c12m5_cornfield", "zoey"): BASE_ID + 203,
    ("c12m5_cornfield", "louis"): BASE_ID + 204,
    
    # Cold Stream
    ("c13m1_alpinecreek", "ellis"): BASE_ID + 205,
    ("c13m1_alpinecreek", "rochelle"): BASE_ID + 206,
    ("c13m1_alpinecreek", "coach"): BASE_ID + 207,
    ("c13m1_alpinecreek", "nick"): BASE_ID + 208,
    ("c13m2_southpinestream", "ellis"): BASE_ID + 209,
    ("c13m2_southpinestream", "rochelle"): BASE_ID + 210,
    ("c13m2_southpinestream", "coach"): BASE_ID + 211,
    ("c13m2_southpinestream", "nick"): BASE_ID + 212,
    ("c13m3_memorialbridge", "ellis"): BASE_ID + 213,
    ("c13m3_memorialbridge", "rochelle"): BASE_ID + 214,
    ("c13m3_memorialbridge", "coach"): BASE_ID + 215,
    ("c13m3_memorialbridge", "nick"): BASE_ID + 216,
    ("c13m4_cutthroatcreek", "ellis"): BASE_ID + 217,
    ("c13m4_cutthroatcreek", "rochelle"): BASE_ID + 218,
    ("c13m4_cutthroatcreek", "coach"): BASE_ID + 219,
    ("c13m4_cutthroatcreek", "nick"): BASE_ID + 220,
    
    # The Last Stand
    ("c14m1_junkyard", "francis"): BASE_ID + 221,
    ("c14m1_junkyard", "bill"): BASE_ID + 222,
    ("c14m1_junkyard", "zoey"): BASE_ID + 223,
    ("c14m1_junkyard", "louis"): BASE_ID + 224,
    ("c14m2_lighthouse", "francis"): BASE_ID + 225,
    ("c14m2_lighthouse", "bill"): BASE_ID + 226,
    ("c14m2_lighthouse", "zoey"): BASE_ID + 227,
    ("c14m2_lighthouse", "louis"): BASE_ID + 228,
    
    # Extra Locations - Dark Carnival minigames
    ("c2m2_fairgrounds", "moustachio_strength"): BASE_ID + 229,
    ("c2m3_coaster", "moustachio_whack"): BASE_ID + 230,
    ("c2m1_highway", "gnome_chompski"): BASE_ID + 231,
}

def get_location_id(map_name, character_name):
    """Get location ID for a map and character combination"""
    key = (map_name, character_name.lower())
    return LOCATION_MAP.get(key)

def get_all_location_ids():
    """Get all location IDs"""
    return list(LOCATION_MAP.values())