from typing import Dict, TYPE_CHECKING
import logging

# You need to import the BaseClasses.py from Archipelago's core
from .Types import LocData

if TYPE_CHECKING:
    from . import L4D2World

base_id = 69420000

# Consolidate all location definitions into a single dictionary
location_table = {
    # Replace simple integer values with LocData objects
    # LocData(ap_code: int, name: str, type: str)
    "Dead Center - Safe Room 1(Ellis)": LocData(base_id + 0, "Dead Center - Safe Room 1(Ellis)", "Progression"),
    "Dead Center - Safe Room 1(Rochelle)": LocData(base_id + 1, "Dead Center - Safe Room 1(Rochelle)", "Progression"),
    "Dead Center - Safe Room 1(Coach)": LocData(base_id + 2, "Dead Center - Safe Room 1(Coach)", "Progression"),
    "Dead Center - Safe Room 1(Nick)": LocData(base_id + 3, "Dead Center - Safe Room 1(Nick)", "Progression"),
    "Dead Center - Safe Room 2(Ellis)": LocData(base_id + 4, "Dead Center - Safe Room 2(Ellis)", "Progression"),
    "Dead Center - Safe Room 2(Rochelle)": LocData(base_id + 5, "Dead Center - Safe Room 2(Rochelle)", "Progression"),
    "Dead Center - Safe Room 2(Coach)": LocData(base_id + 6, "Dead Center - Safe Room 2(Coach)", "Progression"),
    "Dead Center - Safe Room 2(Nick)": LocData(base_id + 7, "Dead Center - Safe Room 2(Nick)", "Progression"),
    "Dead Center - Safe Room 3(Ellis)": LocData(base_id + 8, "Dead Center - Safe Room 3(Ellis)", "Progression"),
    "Dead Center - Safe Room 3(Rochelle)": LocData(base_id + 9, "Dead Center - Safe Room 3(Rochelle)", "Progression"),
    "Dead Center - Safe Room 3(Coach)": LocData(base_id + 10, "Dead Center - Safe Room 3(Coach)", "Progression"),
    "Dead Center - Safe Room 3(Nick)": LocData(base_id + 11, "Dead Center - Safe Room 3(Nick)", "Progression"),
    "Dead Center - Atrium Finale(Ellis)": LocData(base_id + 12, "Dead Center - Atrium Finale(Ellis)", "Progression"),
    "Dead Center - Atrium Finale(Rochelle)": LocData(base_id + 13, "Dead Center - Atrium Finale(Rochelle)", "Progression"),
    "Dead Center - Atrium Finale(Coach)": LocData(base_id + 14, "Dead Center - Atrium Finale(Coach)", "Progression"),
    "Dead Center - Atrium Finale(Nick)": LocData(base_id + 15, "Dead Center - Atrium Finale(Nick)", "Progression"),
    "Dead Center - Cola Bottle Spot": LocData(base_id + 16, "Dead Center - Cola Bottle Spot", "Progression"),   
    "The Passing - Safe Room 1(Ellis)": LocData(base_id + 17, "The Passing - Safe Room 1(Ellis)", "Progression"),
    "The Passing - Safe Room 1(Rochelle)": LocData(base_id + 18, "The Passing - Safe Room 1(Rochelle)", "Progression"),
    "The Passing - Safe Room 1(Coach)": LocData(base_id + 19, "The Passing - Safe Room 1(Coach)", "Progression"),
    "The Passing - Safe Room 1(Nick)": LocData(base_id + 20, "The Passing - Safe Room 1(Nick)", "Progression"),
    "The Passing - Safe Room 2(Ellis)": LocData(base_id + 21, "The Passing - Safe Room 2(Ellis)", "Progression"),
    "The Passing - Safe Room 2(Coach)": LocData(base_id + 22, "The Passing - Safe Room 2(Coach)", "Progression"),
    "The Passing - Safe Room 2(Rochelle)": LocData(base_id + 23, "The Passing - Safe Room 2(Rochelle)", "Progression"),
    "The Passing - Safe Room 2(Nick)": LocData(base_id + 24, "The Passing - Safe Room 2(Nick)", "Progression"),
    "The Passing - Port Finale(Ellis)": LocData(base_id + 25, "The Passing - Port Finale(Ellis)", "Progression"),
    "The Passing - Port Finale(Rochelle)": LocData(base_id + 26, "The Passing - Port Finale(Rochelle)", "Progression"),
    "The Passing - Port Finale(Coach)": LocData(base_id + 27, "The Passing - Port Finale(Coach)", "Progression"),
    "The Passing - Port Finale(Nick)": LocData(base_id + 28, "The Passing - Port Finale(Nick)", "Progression"),
    "Dark Carnival - Safe Room 1(Ellis)": LocData(base_id + 29, "Dark Carnival - Safe Room 1(Ellis)", "Progression"),
    "Dark Carnival - Safe Room 1(Coach)": LocData(base_id + 30, "Dark Carnival - Safe Room 1(Coach)", "Progression"),
    "Dark Carnival - Safe Room 1(Rochelle)": LocData(base_id + 31, "Dark Carnival - Safe Room 1(Rochelle)", "Progression"),
    "Dark Carnival - Safe Room 1(Nick)": LocData(base_id + 32, "Dark Carnival - Safe Room 1(Nick)", "Progression"),
    "Dark Carnival - Safe Room 2(Ellis)": LocData(base_id + 33, "Dark Carnival - Safe Room 2(Ellis)", "Progression"),
    "Dark Carnival - Safe Room 2(Coach)": LocData(base_id + 34, "Dark Carnival - Safe Room 2(Coach)", "Progression"),
    "Dark Carnival - Safe Room 2(Rochelle)": LocData(base_id + 35, "Dark Carnival - Safe Room 2(Rochelle)", "Progression"),
    "Dark Carnival - Safe Room 2(Nick)": LocData(base_id + 36, "Dark Carnival - Safe Room 2(Nick)", "Progression"),
    "Dark Carnival - Safe Room 3(Ellis)": LocData(base_id + 37, "Dark Carnival - Safe Room 3(Ellis)", "Progression"),
    "Dark Carnival - Safe Room 3(Coach)": LocData(base_id + 38, "Dark Carnival - Safe Room 3(Coach)", "Progression"),
    "Dark Carnival - Safe Room 3(Rochelle)": LocData(base_id + 39, "Dark Carnival - Safe Room 3(Rochelle)", "Progression"),
    "Dark Carnival - Safe Room 3(Nick)": LocData(base_id + 40, "Dark Carnival - Safe Room 3(Nick)", "Progression"),
    "Dark Carnival - Safe Room 4(Ellis)": LocData(base_id + 41, "Dark Carnival - Safe Room 4(Ellis)", "Progression"),
    "Dark Carnival - Safe Room 4(Coach)": LocData(base_id + 42, "Dark Carnival - Safe Room 4(Coach)", "Progression"),
    "Dark Carnival - Safe Room 4(Rochelle)": LocData(base_id + 43, "Dark Carnival - Safe Room 4(Rochelle)", "Progression"),
    "Dark Carnival - Safe Room 4(Nick)": LocData(base_id + 44, "Dark Carnival - Safe Room 4(Nick)", "Progression"),
    "Dark Carnival - Concert Finale(Ellis)": LocData(base_id + 45, "Dark Carnival - Concert Finale(Ellis)", "Progression"),
    "Dark Carnival - Concert Finale(Coach)": LocData(base_id + 46, "Dark Carnival - Concert Finale(Coach)", "Progression"),
    "Dark Carnival - Concert Finale(Rochelle)": LocData(base_id + 47, "Dark Carnival - Concert Finale(Rochelle)", "Progression"),
    "Dark Carnival - Concert Finale(Nick)": LocData(base_id + 48, "Dark Carnival - Concert Finale(Nick)", "Progression"),
    "Swamp Fever - Safe Room 1(Ellis)": LocData(base_id + 49, "Swamp Fever - Safe Room 1(Ellis)", "Progression"),
    "Swamp Fever - Safe Room 1(Coach)": LocData(base_id + 50, "Swamp Fever - Safe Room 1(Coach)", "Progression"),
    "Swamp Fever - Safe Room 1(Rochelle)": LocData(base_id + 51, "Swamp Fever - Safe Room 1(Rochelle)", "Progression"),
    "Swamp Fever - Safe Room 1(Nick)": LocData(base_id + 52, "Swamp Fever - Safe Room 1(Nick)", "Progression"),
    "Swamp Fever - Safe Room 2(Ellis)": LocData(base_id + 53, "Swamp Fever - Safe Room 2(Ellis)", "Progression"),
    "Swamp Fever - Safe Room 2(Coach)": LocData(base_id + 54, "Swamp Fever - Safe Room 2(Coach)", "Progression"),
    "Swamp Fever - Safe Room 2(Rochelle)": LocData(base_id + 55, "Swamp Fever - Safe Room 2(Rochelle)", "Progression"),
    "Swamp Fever - Safe Room 2(Nick)": LocData(base_id + 56, "Swamp Fever - Safe Room 2(Nick)", "Progression"),
    "Swamp Fever - Safe Room 3(Ellis)": LocData(base_id + 57, "Swamp Fever - Safe Room 3(Ellis)", "Progression"),
    "Swamp Fever - Safe Room 3(Coach)": LocData(base_id + 58, "Swamp Fever - Safe Room 3(Coach)", "Progression"),
    "Swamp Fever - Safe Room 3(Rochelle)": LocData(base_id + 59, "Swamp Fever - Safe Room 3(Rochelle)", "Progression"),
    "Swamp Fever - Safe Room 3(Nick)": LocData(base_id + 60, "Swamp Fever - Safe Room 3(Nick)", "Progression"),
    "Swamp Fever - Plantation Finale(Ellis)": LocData(base_id + 61, "Swamp Fever - Plantation Finale(Ellis)", "Progression"),
    "Swamp Fever - Plantation Finale(Coach)": LocData(base_id + 62, "Swamp Fever - Plantation Finale(Coach)", "Progression"),
    "Swamp Fever - Plantation Finale(Rochelle)": LocData(base_id + 63, "Swamp Fever - Plantation Finale(Rochelle)", "Progression"),
    "Swamp Fever - Plantation Finale(Nick)": LocData(base_id + 64, "Swamp Fever - Plantation Finale(Nick)", "Progression"),
    "Hard Rain - Safe Room 1(Ellis)": LocData(base_id + 65, "Hard Rain - Safe Room 1(Ellis)", "Progression"),
    "Hard Rain - Safe Room 1(Coach)": LocData(base_id + 66, "Hard Rain - Safe Room 1(Coach)", "Progression"),
    "Hard Rain - Safe Room 1(Rochelle)": LocData(base_id + 67, "Hard Rain - Safe Room 1(Rochelle)", "Progression"),
    "Hard Rain - Safe Room 1(Nick)": LocData(base_id + 68, "Hard Rain - Safe Room 1(Nick)", "Progression"),
    "Hard Rain - Safe Room 2(Ellis)": LocData(base_id + 69, "Hard Rain - Safe Room 2(Ellis)", "Progression"),
    "Hard Rain - Safe Room 2(Coach)": LocData(base_id + 70, "Hard Rain - Safe Room 2(Coach)", "Progression"),
    "Hard Rain - Safe Room 2(Rochelle)": LocData(base_id + 71, "Hard Rain - Safe Room 2(Rochelle)", "Progression"),
    "Hard Rain - Safe Room 2(Nick)": LocData(base_id + 72, "Hard Rain - Safe Room 2(Nick)", "Progression"),
    "Hard Rain - Safe Room 3(Ellis)": LocData(base_id + 73, "Hard Rain - Safe Room 3(Ellis)", "Progression"),
    "Hard Rain - Safe Room 3(Coach)": LocData(base_id + 74, "Hard Rain - Safe Room 3(Coach)", "Progression"),
    "Hard Rain - Safe Room 3(Rochelle)": LocData(base_id + 75, "Hard Rain - Safe Room 3(Rochelle)", "Progression"),
    "Hard Rain - Safe Room 3(Nick)": LocData(base_id + 76, "Hard Rain - Safe Room 3(Nick)", "Progression"),
    "Hard Rain - Safe Room 4(Ellis)": LocData(base_id + 77, "Hard Rain - Safe Room 4(Ellis)", "Progression"),
    "Hard Rain - Safe Room 4(Coach)": LocData(base_id + 78, "Hard Rain - Safe Room 4(Coach)", "Progression"),
    "Hard Rain - Safe Room 4(Rochelle)": LocData(base_id + 79, "Hard Rain - Safe Room 4(Rochelle)", "Progression"),
    "Hard Rain - Safe Room 4(Nick)": LocData(base_id + 80, "Hard Rain - Safe Room 4(Nick)", "Progression"),
    "Hard Rain - Town Escape Finale(Ellis)": LocData(base_id + 81, "HardRain - TownEscape Finale(Ellis)", "Progression"),
    "Hard Rain - Town Escape Finale(Coach)": LocData(base_id + 82, "HardRain - TownEscape Finale(Coach)", "Progression"),
    "Hard Rain - Town Escape Finale(Rochelle)": LocData(base_id + 83, "HardRain - TownEscape Finale(Rochelle)", "Progression"),
    "Hard Rain - Town Escape Finale(Nick)": LocData(base_id + 84, "HardRain - TownEscape Finale(Nick)", "Progression"),
    "The Parish - Safe Room 1(Ellis)": LocData(base_id + 85, "The Parish - Safe Room 1(Ellis)", "Progression"),
    "The Parish - Safe Room 1(Coach)": LocData(base_id + 86, "The Parish - Safe Room 1(Coach)", "Progression"),
    "The Parish - Safe Room 1(Rochelle)": LocData(base_id + 87, "The Parish - Safe Room 1(Rochelle)", "Progression"),
    "The Parish - Safe Room 1(Nick)": LocData(base_id + 88, "The Parish - Safe Room 1(Nick)", "Progression"),
    "The Parish - Safe Room 2(Ellis)": LocData(base_id + 89, "The Parish - Safe Room 2(Ellis)", "Progression"),
    "The Parish - Safe Room 2(Coach)": LocData(base_id + 90, "The Parish - Safe Room 2(Coach)", "Progression"),
    "The Parish - Safe Room 2(Rochelle)": LocData(base_id + 91, "The Parish - Safe Room 2(Rochelle)", "Progression"),
    "The Parish - Safe Room 2(Nick)": LocData(base_id + 92, "The Parish - Safe Room 2(Nick)", "Progression"),
    "The Parish - Safe Room 3(Ellis)": LocData(base_id + 93, "The Parish - Safe Room 3(Ellis)", "Progression"),
    "The Parish - Safe Room 3(Coach)": LocData(base_id + 94, "The Parish - Safe Room 3(Coach)", "Progression"),
    "The Parish - Safe Room 3(Rochelle)": LocData(base_id + 95, "The Parish - Safe Room 3(Rochelle)", "Progression"),
    "The Parish - Safe Room 3(Nick)": LocData(base_id + 96, "The Parish - Safe Room 3(Nick)", "Progression"),
    "The Parish - Safe Room 4(Ellis)": LocData(base_id + 97, "The Parish - Safe Room 4(Ellis)", "Progression"),
    "The Parish - Safe Room 4(Coach)": LocData(base_id + 98, "The Parish - Safe Room 4(Coach)", "Progression"),
    "The Parish - Safe Room 4(Rochelle)": LocData(base_id + 99, "The Parish - Safe Room 4(Rochelle)", "Progression"),
    "The Parish - Safe Room 4(Nick)": LocData(base_id + 100, "The Parish - Safe Room 4(Nick)", "Progression"),
    "The Parish - Bridge Finale(Ellis)": LocData(base_id + 101, "The Parish - Bridge Finale(Ellis)", "Progression"),
    "The Parish - Bridge Finale(Coach)": LocData(base_id + 102, "The Parish - Bridge Finale(Coach)", "Progression"),
    "The Parish - Bridge Finale(Rochelle)": LocData(base_id + 103, "The Parish - Bridge Finale(Rochelle)", "Progression"),
    "The Parish - Bridge Finale(Nick)": LocData(base_id + 104, "The Parish - Bridge Finale(Nick)", "Progression"),
    "The Sacrifice - Safe Room 1(Francis)": LocData(base_id + 105, "The Sacrifice - Safe Room 1(Francis)", "Progression"),
    "The Sacrifice - Safe Room 1(Bill)": LocData(base_id + 106, "The Sacrifice - Safe Room 1(Bill)", "Progression"),
    "The Sacrifice - Safe Room 1(Zoey)": LocData(base_id + 107, "The Sacrifice - Safe Room 1(Zoey)", "Progression"),
    "The Sacrifice - Safe Room 1(Louis)": LocData(base_id + 108, "The Sacrifice - Safe Room 1(Louis)", "Progression"),
    "The Sacrifice - Safe Room 2(Francis)": LocData(base_id + 109, "The Sacrifice - Safe Room 2(Francis)", "Progression"),
    "The Sacrifice - Safe Room 2(Bill)": LocData(base_id + 110, "The Sacrifice - Safe Room 2(Bill)", "Progression"),
    "The Sacrifice - Safe Room 2(Zoey)": LocData(base_id + 111, "The Sacrifice - Safe Room 2(Zoey)", "Progression"),
    "The Sacrifice - Safe Room 2(Louis)": LocData(base_id + 112, "The Sacrifice - Safe Room 2(Louis)", "Progression"),
    "The Sacrifice - Port Finale(Francis)": LocData(base_id + 113, "The Sacrifice - Port Finale(Francis)", "Progression"),
    "The Sacrifice - Port Finale(Bill)": LocData(base_id + 114, "The Sacrifice - Port Finale(Bill)", "Progression"),
    "The Sacrifice - Port Finale(Zoey)": LocData(base_id + 115, "The Sacrifice - Port Finale(Zoey)", "Progression"),
    "The Sacrifice - Port Finale(Louis)": LocData(base_id + 116, "The Sacrifice - Port Finale(Louis)", "Progression"),
    "No Mercy - Safe Room 1(Francis)": LocData(base_id + 117, "No Mercy - Safe Room 1(Francis)", "Progression"),
    "No Mercy - Safe Room 1(Bill)": LocData(base_id + 118, "No Mercy - Safe Room 1(Bill)", "Progression"),
    "No Mercy - Safe Room 1(Zoey)": LocData(base_id + 119, "No Mercy - Safe Room 1(Zoey)", "Progression"),
    "No Mercy - Safe Room 1(Louis)": LocData(base_id + 120, "No Mercy - Safe Room 1(Louis)", "Progression"),
    "No Mercy - Safe Room 2(Francis)": LocData(base_id + 121, "No Mercy - Safe Room 2(Francis)", "Progression"),
    "No Mercy - Safe Room 2(Bill)": LocData(base_id + 122, "No Mercy - Safe Room 2(Bill)", "Progression"),
    "No Mercy - Safe Room 2(Zoey)": LocData(base_id + 123, "No Mercy - Safe Room 2(Zoey)", "Progression"),
    "No Mercy - Safe Room 2(Louis)": LocData(base_id + 124, "No Mercy - Safe Room 2(Louis)", "Progression"),
    "No Mercy - Safe Room 3(Francis)": LocData(base_id + 125, "No Mercy - Safe Room 3(Francis)", "Progression"),
    "No Mercy - Safe Room 3(Bill)": LocData(base_id + 126, "No Mercy - Safe Room 3(Bill)", "Progression"),
    "No Mercy - Safe Room 3(Zoey)": LocData(base_id + 127, "No Mercy - Safe Room 3(Zoey)", "Progression"),
    "No Mercy - Safe Room 3(Louis)": LocData(base_id + 128, "No Mercy - Safe Room 3(Louis)", "Progression"),
    "No Mercy - Safe Room 4(Francis)": LocData(base_id + 129, "No Mercy - Safe Room 4(Francis)", "Progression"),
    "No Mercy - Safe Room 4(Bill)": LocData(base_id + 130, "No Mercy - Safe Room 4(Bill)", "Progression"),
    "No Mercy - Safe Room 4(Zoey)": LocData(base_id + 131, "No Mercy - Safe Room 4(Zoey)", "Progression"),
    "No Mercy - Safe Room 4(Louis)": LocData(base_id + 132, "No Mercy - Safe Room 4(Louis)", "Progression"),
    "No Mercy - Rooftop Finale(Francis)": LocData(base_id + 133, "No Mercy - Rooftop Finale(Francis)", "Progression"),
    "No Mercy - Rooftop Finale(Bill)": LocData(base_id + 134, "No Mercy - Rooftop Finale(Bill)", "Progression"),
    "No Mercy - Rooftop Finale(Zoey)": LocData(base_id + 135, "No Mercy - Rooftop Finale(Zoey)", "Progression"),
    "No Mercy - Rooftop Finale(Louis)": LocData(base_id + 136, "No Mercy - Rooftop Finale(Louis)", "Progression"),
    "Crash Course - Safe Room 1(Francis)": LocData(base_id + 137, "Crash Course - Safe Room 1(Francis)", "Progression"),
    "Crash Course - Safe Room 1(Bill)": LocData(base_id + 138, "Crash Course - Safe Room 1(Bill)", "Progression"),
    "Crash Course - Safe Room 1(Zoey)": LocData(base_id + 139, "Crash Course - Safe Room 1(Zoey)", "Progression"),
    "Crash Course - Safe Room 1(Louis)": LocData(base_id + 140, "Crash Course - Safe Room 1(Louis)", "Progression"),
    "Crash Course - Truck Depot Finale(Francis)": LocData(base_id + 141, "Crash Course - Truck Depot Finale(Francis)", "Progression"),
    "Crash Course - Truck Depot Finale(Bill)": LocData(base_id + 142, "Crash Course - Truck Depot Finale(Bill)", "Progression"),
    "Crash Course - Truck Depot Finale(Zoey)": LocData(base_id + 143, "Crash Course - Truck Depot Finale(Zoey)", "Progression"),
    "Crash Course - Truck Depot Finale(Louis)": LocData(base_id + 144, "Crash Course - Truck Depot Finale(Louis)", "Progression"),
    "Death Toll - Safe Room 1(Francis)": LocData(base_id + 145, "Death Toll - Safe Room 1(Francis)", "Progression"),
    "Death Toll - Safe Room 1(Bill)": LocData(base_id + 146, "Death Toll - Safe Room 1(Bill)", "Progression"),
    "Death Toll - Safe Room 1(Zoey)": LocData(base_id + 147, "Death Toll - Safe Room 1(Zoey)", "Progression"),
    "Death Toll - Safe Room 1(Louis)": LocData(base_id + 148, "Death Toll - Safe Room 1(Louis)", "Progression"),
    "Death Toll - Safe Room 2(Francis)": LocData(base_id + 149, "Death Toll - Safe Room 2(Francis)", "Progression"),
    "Death Toll - Safe Room 2(Bill)": LocData(base_id + 150, "Death Toll - Safe Room 2(Bill)", "Progression"),
    "Death Toll - Safe Room 2(Zoey)": LocData(base_id + 151, "Death Toll - Safe Room 2(Zoey)", "Progression"),
    "Death Toll - Safe Room 2(Louis)": LocData(base_id + 152, "Death Toll - Safe Room 2(Louis)", "Progression"),
    "Death Toll - Safe Room 3(Francis)": LocData(base_id + 153, "Death Toll - Safe Room 3(Francis)", "Progression"),
    "Death Toll - Safe Room 3(Bill)": LocData(base_id + 154, "Death Toll - Safe Room 3(Bill)", "Progression"),
    "Death Toll - Safe Room 3(Zoey)": LocData(base_id + 155, "Death Toll - Safe Room 3(Zoey)", "Progression"),
    "Death Toll - Safe Room 3(Louis)": LocData(base_id + 156, "Death Toll - Safe Room 3(Louis)", "Progression"),
    "Death Toll - Safe Room 4(Francis)": LocData(base_id + 157, "Death Toll - Safe Room 4(Francis)", "Progression"),
    "Death Toll - Safe Room 4(Bill)": LocData(base_id + 158, "Death Toll - Safe Room 4(Bill)", "Progression"),
    "Death Toll - Safe Room 4(Zoey)": LocData(base_id + 159, "Death Toll - Safe Room 4(Zoey)", "Progression"),
    "Death Toll - Safe Room 4(Louis)": LocData(base_id + 160, "Death Toll - Safe Room 4(Louis)", "Progression"),
    "Death Toll - Boathouse Finale(Francis)": LocData(base_id + 161, "Death Toll - Boathouse Finale(Francis)", "Progression"),
    "Death Toll - Boathouse Finale(Bill)": LocData(base_id + 162, "Death Toll - Boathouse Finale(Bill)", "Progression"),
    "Death Toll - Boathouse Finale(Zoey)": LocData(base_id + 163, "Death Toll - Boathouse Finale(Zoey)", "Progression"),
    "Death Toll - Boathouse Finale(Louis)": LocData(base_id + 164, "Death Toll - Boathouse Finale(Louis)", "Progression"),
    "Dead Air - Safe Room 1(Francis)": LocData(base_id + 165, "Dead Air - Safe Room 1(Francis)", "Progression"),
    "Dead Air - Safe Room 1(Bill)": LocData(base_id + 166, "Dead Air - Safe Room 1(Bill)", "Progression"),
    "Dead Air - Safe Room 1(Zoey)": LocData(base_id + 167, "Dead Air - Safe Room 1(Zoey)", "Progression"),
    "Dead Air - Safe Room 1(Louis)": LocData(base_id + 168, "Dead Air - Safe Room 1(Louis)", "Progression"),
    "Dead Air - Safe Room 2(Francis)": LocData(base_id + 169, "Dead Air - Safe Room 2(Francis)", "Progression"),
    "Dead Air - Safe Room 2(Bill)": LocData(base_id + 170, "Dead Air - Safe Room 2(Bill)", "Progression"),
    "Dead Air - Safe Room 2(Zoey)": LocData(base_id + 171, "Dead Air - Safe Room 2(Zoey)", "Progression"),
    "Dead Air - Safe Room 2(Louis)": LocData(base_id + 172, "Dead Air - Safe Room 2(Louis)", "Progression"),
    "Dead Air - Safe Room 3(Francis)": LocData(base_id + 173, "Dead Air - Safe Room 3(Francis)", "Progression"),
    "Dead Air - Safe Room 3(Bill)": LocData(base_id + 174, "Dead Air - Safe Room 3(Bill)", "Progression"),
    "Dead Air - Safe Room 3(Zoey)": LocData(base_id + 175, "Dead Air - Safe Room 3(Zoey)", "Progression"),
    "Dead Air - Safe Room 3(Louis)": LocData(base_id + 176, "Dead Air - Safe Room 3(Louis)", "Progression"),
    "Dead Air - Safe Room 4(Francis)": LocData(base_id + 177, "Dead Air - Safe Room 4(Francis)", "Progression"),
    "Dead Air - Safe Room 4(Bill)": LocData(base_id + 178, "Dead Air - Safe Room 4(Bill)", "Progression"),
    "Dead Air - Safe Room 4(Zoey)": LocData(base_id + 179, "Dead Air - Safe Room 4(Zoey)", "Progression"),
    "Dead Air - Safe Room 4(Louis)": LocData(base_id + 180, "Dead Air - Safe Room 4(Louis)", "Progression"),
    "Dead Air - Runway Finale(Francis)": LocData(base_id + 181, "Dead Air - Runway Finale(Francis)", "Progression"),
    "Dead Air - Runway Finale(Bill)": LocData(base_id + 182, "Dead Air - Runway Finale(Bill)", "Progression"),
    "Dead Air - Runway Finale(Zoey)": LocData(base_id + 183, "Dead Air - Runway Finale(Zoey)", "Progression"),
    "Dead Air - Runway Finale(Louis)": LocData(base_id + 184, "Dead Air - Runway Finale(Louis)", "Progression"),
    "Blood Harvest - Safe Room 1(Francis)": LocData(base_id + 185, "Blood Harvest - Safe Room 1(Francis)", "Progression"),
    "Blood Harvest - Safe Room 1(Bill)": LocData(base_id + 186, "Blood Harvest - Safe Room 1(Bill)", "Progression"),
    "Blood Harvest - Safe Room 1(Zoey)": LocData(base_id + 187, "Blood Harvest - Safe Room 1(Zoey)", "Progression"),
    "Blood Harvest - Safe Room 1(Louis)": LocData(base_id + 188, "Blood Harvest - Safe Room 1(Louis)", "Progression"),
    "Blood Harvest - Safe Room 2(Francis)": LocData(base_id + 189, "Blood Harvest - Safe Room 2(Francis)", "Progression"),
    "Blood Harvest - Safe Room 2(Bill)": LocData(base_id + 190, "Blood Harvest - Safe Room 2(Bill)", "Progression"),
    "Blood Harvest - Safe Room 2(Zoey)": LocData(base_id + 191, "Blood Harvest - Safe Room 2(Zoey)", "Progression"),
    "Blood Harvest - Safe Room 2(Louis)": LocData(base_id + 192, "Blood Harvest - Safe Room 2(Louis)", "Progression"),
    "Blood Harvest - Safe Room 3(Francis)": LocData(base_id + 193, "Blood Harvest - Safe Room 3(Francis)", "Progression"),
    "Blood Harvest - Safe Room 3(Bill)": LocData(base_id + 194, "Blood Harvest - Safe Room 3(Bill)", "Progression"),
    "Blood Harvest - Safe Room 3(Zoey)": LocData(base_id + 195, "Blood Harvest - Safe Room 3(Zoey)", "Progression"),
    "Blood Harvest - Safe Room 3(Louis)": LocData(base_id + 196, "Blood Harvest - Safe Room 3(Louis)", "Progression"),
    "Blood Harvest - Safe Room 4(Francis)": LocData(base_id + 197, "Blood Harvest - Safe Room 4(Francis)", "Progression"),
    "Blood Harvest - Safe Room 4(Bill)": LocData(base_id + 198, "Blood Harvest - Safe Room 4(Bill)", "Progression"),
    "Blood Harvest - Safe Room 4(Zoey)": LocData(base_id + 199, "Blood Harvest - Safe Room 4(Zoey)", "Progression"),
    "Blood Harvest - Safe Room 4(Louis)": LocData(base_id + 200, "Blood Harvest - Safe Room 4(Louis)", "Progression"),
    "Blood Harvest - Farmhouse Finale(Francis)": LocData(base_id + 201, "Blood Harvest - Farmhouse Finale(Francis)", "Progression"),
    "Blood Harvest - Farmhouse Finale(Bill)": LocData(base_id + 202, "Blood Harvest - Farmhouse Finale(Bill)", "Progression"),
    "Blood Harvest - Farmhouse Finale(Zoey)": LocData(base_id + 203, "Blood Harvest - Farmhouse Finale(Zoey)", "Progression"),
    "Blood Harvest - Farmhouse Finale(Louis)": LocData(base_id + 204, "Blood Harvest - Farmhouse Finale(Louis)", "Progression"),
    "Cold Stream - Safe Room 1(Ellis)": LocData(base_id + 205, "Cold Stream - Safe Room 1(Ellis)", "Progression"),
    "Cold Stream - Safe Room 1(Coach)": LocData(base_id + 206, "Cold Stream - Safe Room 1(Coach)", "Progression"),
    "Cold Stream - Safe Room 1(Rochelle)": LocData(base_id + 207, "Cold Stream - Safe Room 1(Rochelle)", "Progression"),
    "Cold Stream - Safe Room 1(Nick)": LocData(base_id + 208, "Cold Stream - Safe Room 1(Nick)", "Progression"),
    "Cold Stream - Safe Room 2(Ellis)": LocData(base_id + 209, "Cold Stream - Safe Room 2(Ellis)", "Progression"),
    "Cold Stream - Safe Room 2(Coach)": LocData(base_id + 210, "Cold Stream - Safe Room 2(Coach)", "Progression"),
    "Cold Stream - Safe Room 2(Rochelle)": LocData(base_id + 211, "Cold Stream - Safe Room 2(Rochelle)", "Progression"),
    "Cold Stream - Safe Room 2(Nick)": LocData(base_id + 212, "Cold Stream - Safe Room 2(Nick)", "Progression"),
    "Cold Stream - Safe Room 3(Ellis)": LocData(base_id + 213, "Cold Stream - Safe Room 3(Ellis)", "Progression"),
    "Cold Stream - Safe Room 3(Coach)": LocData(base_id + 214, "Cold Stream - Safe Room 3(Coach)", "Progression"),
    "Cold Stream - Safe Room 3(Rochelle)": LocData(base_id + 215, "Cold Stream - Safe Room 3(Rochelle)", "Progression"),
    "Cold Stream - Safe Room 3(Nick)": LocData(base_id + 216, "Cold Stream - Safe Room 3(Nick)", "Progression"),
    "Cold Stream - Cut Throat Creek Finale(Ellis)": LocData(base_id + 217, "Cold Stream - Cut Throat Creek Finale(Ellis)", "Progression"),
    "Cold Stream - Cut Throat Creek Finale(Coach)": LocData(base_id + 218, "Cold Stream - Cut Throat Creek Finale(Coach)", "Progression"),
    "Cold Stream - Cut Throat Creek Finale(Rochelle)": LocData(base_id + 219, "Cold Stream - Cut Throat Creek Finale(Rochelle)", "Progression"),
    "Cold Stream - Cut Throat Creek Finale(Nick)": LocData(base_id + 220, "Cold Stream - Cut Throat Creek Finale(Nick)", "Progression"),
    "The Last Stand - Safe Room 1(Francis)": LocData(base_id + 221, "The Last Stand - Safe Room 1(Francis)", "Progression"),
    "The Last Stand - Safe Room 1(Bill)": LocData(base_id + 222, "The Last Stand - Safe Room 1(Bill)", "Progression"),
    "The Last Stand - Safe Room 1(Zoey)": LocData(base_id + 223, "The Last Stand - Safe Room 1(Zoey)", "Progression"),
    "The Last Stand - Safe Room 1(Louis)": LocData(base_id + 224, "The Last Stand - Safe Room 1(Louis)", "Progression"),
    "The Last Stand - Lighthouse Finale(Francis)": LocData(base_id + 225, "The Last Stand - Lighthouse Finale(Francis)", "Progression"),
    "The Last Stand - Lighthouse Finale(Bill)": LocData(base_id + 226, "The Last Stand - Lighthouse Finale(Bill)", "Progression"),
    "The Last Stand - Lighthouse Finale(Zoey)": LocData(base_id + 227, "The Last Stand - Lighthouse Finale(Zoey)", "Progression"),
    "The Last Stand - Lighthouse Finale(Louis)": LocData(base_id + 228, "The Last Stand - Lighthouse Finale(Louis)", "Progression"),

    # Extra Locations
    "Moustachio Strength": LocData(base_id + 229, "Moustachio Strength", "Progression"),
    "Moustachio Whack A Mole": LocData(base_id + 230, "Moustachio Whack A Mole", "Progression"),
    "Gnome Chompski": LocData(base_id + 231, "Gnome Chompski", "Progression"),

}

extra_locations = [
    "Moustachio Strength", "Moustachio Whack A Mole", "Gnome Chompski"
]

def did_include_extra_locations(world: "L4D2World") -> bool:
    # Assuming an option exists to toggle extra locations
    # return bool(world.options.ExtraLocations)
    return True # Placeholder for now

def get_total_locations(world: "L4D2World") -> int:
    total = len(location_table)
    if not did_include_extra_locations(world):
        total -= len(extra_locations)
    return total

def get_location_names() -> Dict[str, int]:
    return {name: loc_data.code for name, loc_data in location_table.items()}
